#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from openpilot.selfdrive.test.process_replay.process_replay import CONFIGS, get_custom_params_from_lr, replay_process
from openpilot.selfdrive.test.process_replay.test_processes import EXCLUDED_PROCS
from openpilot.tools.lib.logreader import LogReader, save_log

ALLOW_PROCS = {c.proc_name for c in CONFIGS}


def parse_param_assignments(assignments: list[str]) -> dict[str, bytes]:
  parsed = {}
  for assignment in assignments:
    key, separator, value = assignment.partition("=")
    if not separator or not key:
      raise ValueError(f"invalid parameter assignment: {assignment!r}; expected KEY=VALUE")
    parsed[key] = value.encode()
  return parsed


def build_custom_params(inputs, assignments: list[str]) -> dict:
  custom_params = get_custom_params_from_lr(inputs)
  custom_params.update(parse_param_assignments(assignments))
  return custom_params


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Run process on route and create new logs",
                                   formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument("route", help="The route name to use")
  parser.add_argument("--fingerprint", help="The fingerprint to use")
  parser.add_argument("--whitelist-procs", nargs='*', default=ALLOW_PROCS, help="Whitelist given processes (e.g. controlsd)")
  parser.add_argument("--blacklist-procs", nargs='*', default=EXCLUDED_PROCS, help="Blacklist given processes (e.g. controlsd)")
  parser.add_argument("--set-param", action="append", default=[], metavar="KEY=VALUE",
                      help="Set a parameter in process replay's isolated parameter root (repeatable)")
  args = parser.parse_args()

  allowed_procs = set(args.whitelist_procs) - set(args.blacklist_procs)
  cfgs = [c for c in CONFIGS if c.proc_name in allowed_procs]

  try:
    parse_param_assignments(args.set_param)
  except ValueError as error:
    parser.error(str(error))

  inputs = list(LogReader(args.route))
  custom_params = build_custom_params(inputs, args.set_param)
  outputs = replay_process(cfgs, inputs, fingerprint=args.fingerprint, custom_params=custom_params)

  # Remove message generated by the process under test and merge in the new messages
  produces = {o.which() for o in outputs}
  inputs = [i for i in inputs if i.which() not in produces]
  outputs = sorted(inputs + outputs, key=lambda x: x.logMonoTime)

  fn = f"{args.route.replace('/', '_')}_{'_'.join(allowed_procs)}.zst"
  print(f"Saving log to {fn}")
  save_log(fn, outputs)
